// 统一错误码常量（逐步迁移旧字符串 message 判定）
module.exports = {
  FORM_NOT_FOUND: 'E_FORM_NOT_FOUND',
  FORBIDDEN: 'E_FORBIDDEN',
  INVALID_STATE: 'E_INVALID_STATE',
  INVALID_ITEM: 'E_INVALID_ITEM',
  NO_RECORDS: 'E_NO_RECORDS',
  INVALID_RECORD_IDS: 'E_INVALID_RECORD_IDS',
  UNPROCESSED_RECORDS: 'E_UNPROCESSED_RECORDS',
  LOAN_NOT_FOUND: 'E_LOAN_NOT_FOUND',
  USER_MISMATCH: 'E_USER_MISMATCH',
  LOAN_INVALID_STATUS: 'E_LOAN_INVALID_STATUS',
  LOAN_INSUFFICIENT: 'E_LOAN_INSUFFICIENT',
  // 新增：表单审批相关并发 / 幂等
  CONFLICT: 'E_CONFLICT',            // 乐观锁冲突
  IDEMPOTENT_REPLAY: 'E_IDEMPOTENT_REPLAY' // 重复提交快速返回
};
